name: Variables and Secrets
on: [push]

jobs:
  log-vars:
  runs-on: ${{ vars.JOBS_RUNNER }}
  env:
    BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
    ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
    REPO_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
    ORG_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
  steps:
    - name: Run only if BOOLEAN_SECRET is true
      if: env.BOOLEAN_SECRET == 'true'r
      run: echo "I ran"
    - name: Log Vars
      run: |
        echo '${{ vars.JOBS_RUNNER }}
        ecoh "ORG_LEVEL_VAR: $ORG_LEVEL_VAR"
        ecoh "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
        ecoh "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"